#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
import wave
from pathlib import Path


REQUIRED_FILES = {
    "render_request.json",
    "realized_fragment_sequence.json",
    "note_event_sequence.json",
    "event_transition_sequence.json",
    "synth_event_sequence.json",
    "artifact_summary.json",
    "m1_validation_report.json",
    "offline_audio.wav",
}


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def fail(errors: list[str]) -> int:
    print("stage5 M1 artifact validation failed:")
    for error in errors:
        print(f"- {error}")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate a stage-5 M1 artifact directory generated by musikalisches."
    )
    parser.add_argument(
        "artifact_dir",
        nargs="?",
        default="ops/out/m1-demo",
        help="artifact directory containing render_request.json and related files",
    )
    args = parser.parse_args()

    artifact_dir = Path(args.artifact_dir).resolve()
    errors: list[str] = []

    if not artifact_dir.exists():
        return fail([f"artifact directory does not exist: {artifact_dir}"])

    file_names = {path.name for path in artifact_dir.iterdir() if path.is_file()}
    missing = sorted(REQUIRED_FILES - file_names)
    if missing:
        errors.append(f"missing files: {', '.join(missing)}")
        return fail(errors)

    request_payload = load_json(artifact_dir / "render_request.json")
    realized_payload = load_json(artifact_dir / "realized_fragment_sequence.json")
    note_event_payload = load_json(artifact_dir / "note_event_sequence.json")
    transition_payload = load_json(artifact_dir / "event_transition_sequence.json")
    synth_event_payload = load_json(artifact_dir / "synth_event_sequence.json")
    summary_payload = load_json(artifact_dir / "artifact_summary.json")
    report_payload = load_json(artifact_dir / "m1_validation_report.json")

    if request_payload.get("work_id") != "mozart_dicegame_print_1790s":
        errors.append("render_request.json work_id mismatch")
    if len(request_payload.get("rolls", [])) != 16:
        errors.append("render_request.json must contain 16 selector values")

    if report_payload.get("stage") != "stage5_m1_runtime":
        errors.append("m1_validation_report.json stage must be stage5_m1_runtime")
    if report_payload.get("status") != "passed":
        errors.append("m1_validation_report.json status must be passed")
    if report_payload.get("summary", {}).get("checks_failed") != 0:
        errors.append("m1_validation_report.json checks_failed must equal 0")
    if report_payload.get("summary", {}).get("selector_count") != 16:
        errors.append("m1_validation_report.json selector_count must equal 16")
    if report_payload.get("summary", {}).get("fragment_count") != 16:
        errors.append("m1_validation_report.json fragment_count must equal 16")
    if report_payload.get("summary", {}).get("note_event_count", 0) <= 0:
        errors.append("m1_validation_report.json note_event_count must be > 0")
    if report_payload.get("summary", {}).get("event_transition_count", 0) <= 0:
        errors.append("m1_validation_report.json event_transition_count must be > 0")
    if report_payload.get("summary", {}).get("synth_event_count", 0) <= 0:
        errors.append("m1_validation_report.json synth_event_count must be > 0")
    if not report_payload.get("summary", {}).get("audio_render_backend"):
        errors.append("m1_validation_report.json audio_render_backend must be present")

    fragments = realized_payload.get("fragments", [])
    if len(fragments) != 16:
        errors.append("realized_fragment_sequence.json must contain 16 realized fragments")
    if realized_payload.get("summary", {}).get("fragment_count") != 16:
        errors.append("realized_fragment_sequence.json summary fragment_count must equal 16")

    note_events = note_event_payload.get("note_events", [])
    if not note_events:
        errors.append("note_event_sequence.json must contain note events")
    if note_event_payload.get("summary", {}).get("fragment_count") != 16:
        errors.append("note_event_sequence.json summary fragment_count must equal 16")
    if note_event_payload.get("summary", {}).get("voice_group_count") != 2:
        errors.append("note_event_sequence.json voice_group_count must equal 2")
    if len(note_event_payload.get("voice_groups", [])) != 2:
        errors.append("note_event_sequence.json must expose exactly 2 voice groups")

    transitions = transition_payload.get("transitions", [])
    if not transitions:
        errors.append("event_transition_sequence.json must contain transitions")
    if transition_payload.get("summary", {}).get("note_event_count") != len(note_events):
        errors.append("event_transition_sequence.json note_event_count summary mismatch")
    if transition_payload.get("summary", {}).get("transition_count") != len(transitions):
        errors.append("event_transition_sequence.json transition_count summary mismatch")
    if len(transitions) != len(note_events) * 2:
        errors.append("event_transition_sequence.json must contain exactly 2 transitions per note event")
    if transition_payload.get("summary", {}).get("note_on_count") != len(note_events):
        errors.append("event_transition_sequence.json note_on_count must equal note_event_count")
    if transition_payload.get("summary", {}).get("note_off_count") != len(note_events):
        errors.append("event_transition_sequence.json note_off_count must equal note_event_count")
    if transition_payload.get("summary", {}).get("voice_group_count") != 2:
        errors.append("event_transition_sequence.json voice_group_count must equal 2")
    if len(transition_payload.get("voice_groups", [])) != 2:
        errors.append("event_transition_sequence.json must expose exactly 2 voice groups")
    if any(
        transitions[index]["at_seconds"] > transitions[index + 1]["at_seconds"] + 1e-9
        for index in range(len(transitions) - 1)
    ):
        errors.append("event_transition_sequence.json must remain time-ordered")

    synth_events = synth_event_payload.get("synth_events", [])
    if not synth_events:
        errors.append("synth_event_sequence.json must contain synth events")
    if synth_event_payload.get("summary", {}).get("voice_group_count") != 2:
        errors.append("synth_event_sequence.json voice_group_count must equal 2")
    if synth_event_payload.get("summary", {}).get("note_on_count") != len(note_events):
        errors.append("synth_event_sequence.json note_on_count must equal note_event_count")
    if synth_event_payload.get("summary", {}).get("note_off_count") != len(note_events):
        errors.append("synth_event_sequence.json note_off_count must equal note_event_count")
    if synth_event_payload.get("summary", {}).get("program_change_count") != 2:
        errors.append("synth_event_sequence.json program_change_count must equal 2")
    if synth_event_payload.get("summary", {}).get("synth_event_count") != len(synth_events):
        errors.append("synth_event_sequence.json synth_event_count summary mismatch")
    if len(synth_events) != len(note_events) * 2 + 2:
        errors.append("synth_event_sequence.json must contain 2 setup events plus 2 synth events per note event")
    if any(
        synth_events[index]["at_frame"] > synth_events[index + 1]["at_frame"]
        for index in range(len(synth_events) - 1)
    ):
        errors.append("synth_event_sequence.json must remain frame-ordered")

    if fragments and note_events:
        total_duration = realized_payload.get("total_duration_quarter_length")
        last_note_end = max(event["end_quarter_length"] for event in note_events)
        if last_note_end > total_duration + 1e-9:
            errors.append("note events overrun the realized fragment duration")

    wav_path = artifact_dir / "offline_audio.wav"
    with wave.open(str(wav_path), "rb") as wav_file:
        if wav_file.getframerate() != request_payload.get("sample_rate"):
            errors.append("offline_audio.wav sample rate does not match render_request.json")
        if wav_file.getnchannels() != 2:
            errors.append("offline_audio.wav must be stereo")
        if wav_file.getsampwidth() != 2:
            errors.append("offline_audio.wav must be 16-bit PCM")
        frames = wav_file.getnframes()

    audio_frames = report_payload.get("summary", {}).get("audio_frames")
    if audio_frames != frames:
        errors.append("m1_validation_report.json audio_frames does not match offline_audio.wav")

    if summary_payload.get("note_event_count") != len(note_events):
        errors.append("artifact_summary.json note_event_count mismatch")
    if summary_payload.get("event_transition_count") != len(transitions):
        errors.append("artifact_summary.json event_transition_count mismatch")
    if summary_payload.get("synth_event_count") != len(synth_events):
        errors.append("artifact_summary.json synth_event_count mismatch")
    if summary_payload.get("voice_group_count") != 2:
        errors.append("artifact_summary.json voice_group_count must equal 2")
    if summary_payload.get("audio_present") is not True:
        errors.append("artifact_summary.json audio_present must be true for render-audio outputs")
    if summary_payload.get("fragment_ids") != [fragment["fragment_id"] for fragment in fragments]:
        errors.append("artifact_summary.json fragment_ids must match realized_fragment_sequence.json")

    if errors:
        return fail(errors)

    print("stage5 M1 artifact validation passed")
    print(f"artifact_dir: {artifact_dir}")
    print(f"selector_count: {request_payload['selector_count']}")
    print(f"fragment_count: {len(fragments)}")
    print(f"note_event_count: {len(note_events)}")
    print(f"event_transition_count: {len(transitions)}")
    print(f"synth_event_count: {len(synth_events)}")
    print(f"audio_frames: {frames}")
    print(f"audio_file: {wav_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
